#include-once
#include <WindowsConstants.au3>

Global Const $DM_UPDATE = 1
Global Const $DM_COPY = 2
Global Const $DM_PROMPT = 4
Global Const $DM_MODIFY = 8

Global Const $DM_BITSPERPEL = 0x40000
Global Const $DM_COLLATE = 0x8000
Global Const $DM_COLOR = 0x800
Global Const $DM_COPIES = 0x100

Global Const $DM_DEFAULTSOURCE = 0x200
Global Const $DM_DISPLAYFLAGS = 0x200000
Global Const $DM_DISPLAYFREQUENCY = 0x400000
Global Const $DM_DITHERTYPE = 0x10000000
Global Const $DM_DUPLEX = 0x1000
Global Const $DM_FORMNAME = 0x10000
Global Const $DM_GETDEFID = $WM_USER + 0
Global Const $DM_GRAYSCALE = 0x1
Global Const $DM_ICMINTENT = 0x4000000
Global Const $DM_ICMMETHOD = 0x2000000
Global Const $DM_IN_BUFFER = $DM_MODIFY
Global Const $DM_IN_PROMPT = $DM_PROMPT
Global Const $DM_INTERLACED = 0x2
Global Const $DM_LOGPIXELS = 0x20000
Global Const $DM_MEDIATYPE = 0x8000000

Global Const $DM_NUP = 0x40
Global Const $DM_ORIENTATION = 0x1
Global Const $DM_OUT_BUFFER = $DM_COPY
Global Const $DM_OUT_DEFAULT = $DM_UPDATE
Global Const $DM_PANNINGHEIGHT = 0x10000000
Global Const $DM_PANNINGWIDTH = 0x8000000
Global Const $DM_PAPERLENGTH = 0x4
Global Const $DM_PAPERSIZE = 0x2
Global Const $DM_PAPERWIDTH = 0x8
Global Const $DM_PELSHEIGHT = 0x100000
Global Const $DM_PELSWIDTH = 0x80000
Global Const $DM_POSITION = 0x20
Global Const $DM_PRINTQUALITY = 0x400
Global Const $DM_REPOSITION = ($WM_USER + 2)
Global Const $DM_RESERVED1 = 0x800000
Global Const $DM_RESERVED2 = 0x1000000
Global Const $DM_SCALE = 0x10
Global Const $DM_SETDEFID = $WM_USER + 1
Global Const $DM_SPECVERSION = 0x320

Global Const $DM_TTOPTION = 0x4000
Global Const $DM_YRESOLUTION = 0x2000


Global Const $PD_ALLPAGES = 0x0
Global Const $PD_CAN_DRAW_DIB = 0x1
Global Const $PD_CAN_STRETCHDIB = 0x2
Global Const $PD_COLLATE = 0x10
Global Const $PD_DISABLEPRINTTOFILE = 0x80000
Global Const $PD_CURRENTPAGE = 0x400000
Global Const $PD_ENABLEPRINTHOOK = 0x1000
Global Const $PD_ENABLEPRINTTEMPLATE = 0x4000
Global Const $PD_ENABLEPRINTTEMPLATEHANDLE = 0x10000
Global Const $PD_ENABLESETUPHOOK = 0x2000
Global Const $PD_ENABLESETUPTEMPLATE = 0x8000
Global Const $PD_ENABLESETUPTEMPLATEHANDLE = 0x20000
Global Const $PD_EXCL_COPIESANDCOLLATE = BitOR($DM_COPIES, $DM_COLLATE)
Global Const $PD_EXCLUSIONFLAGS = 0x1000000
;~ Global Const $PD_HDR_LEN As Long = sizeof(POLICY_DATA)
Global Const $PD_HIDEPRINTTOFILE = 0x100000
Global Const $PD_NOCURRENTPAGE = 0x800000
Global Const $PD_NONETWORKBUTTON = 0x200000
Global Const $PD_NOPAGENUMS = 0x8
Global Const $PD_NOSELECTION = 0x4
Global Const $PD_NOWARNING = 0x80
Global Const $PD_PAGENUMS = 0x2
Global Const $PD_PRINTSETUP = 0x40
Global Const $PD_PRINTTOFILE = 0x20
Global Const $PD_RESULT_APPLY = 2
Global Const $PD_RESULT_CANCEL = 0
Global Const $PD_RESULT_PRINT = 1
Global Const $PD_RETURNDC = 0x100
Global Const $PD_RETURNDEFAULT = 0x400
Global Const $PD_RETURNIC = 0x200
Global Const $PD_SELECTION = 0x1
Global Const $PD_SHOWHELP = 0x800
Global Const $PD_STRETCHDIB_1_1_OK = 0x4
Global Const $PD_STRETCHDIB_1_2_OK = 0x8
Global Const $PD_STRETCHDIB_1_N_OK = 0x10
Global Const $PD_USEDEVMODECOPIES = 0x40000
Global Const $PD_USEDEVMODECOPIESANDCOLLATE = 0x40000
Global Const $PD_USELARGETEMPLATE = 0x10000000
Global Const $PDC_NOT_FOUND = 0xC0000083
Global Const $PDC_NOT_RESPONDING = 0xC0000084



;## ERROR-Constants
Global Const $PDERR_CREATEICFAILURE = 0x100A
Global Const $PDERR_DEFAULTDIFFERENT = 0x100C
Global Const $PDERR_DNDMMISMATCH = 0x1009
Global Const $PDERR_GETDEVMODEFAIL = 0x1005
Global Const $PDERR_INITFAILURE = 0x1006
Global Const $PDERR_LOADDRVFAILURE = 0x1004
Global Const $PDERR_NODEFAULTPRN = 0x1008
Global Const $PDERR_NODEVICES = 0x1007
Global Const $PDERR_PARSEFAILURE = 0x1002
Global Const $PDERR_PRINTERCODES = 0x1000
Global Const $PDERR_PRINTERNOTFOUND = 0x100B
Global Const $PDERR_RETDEFFAILURE = 0x1003
Global Const $PDERR_SETUPFAILURE = 0x1001

Global Const $CDERR_DIALOGFAILURE = 0xFFFF
Global Const $CDERR_FINDRESFAILURE = 0x6
Global Const $CDERR_GENERALCODES = 0x0
Global Const $CDERR_INITIALIZATION = 0x2
Global Const $CDERR_LOADRESFAILURE = 0x7
Global Const $CDERR_LOADSTRFAILURE = 0x5
Global Const $CDERR_LOCKRESFAILURE = 0x8
Global Const $CDERR_MEMALLOCFAILURE = 0x9
Global Const $CDERR_MEMLOCKFAILURE = 0xA
Global Const $CDERR_NOHINSTANCE = 0x4
Global Const $CDERR_NOHOOK = 0xB
Global Const $CDERR_NOTEMPLATE = 0x3
Global Const $CDERR_REGISTERMSGFAIL = 0xC
Global Const $CDERR_STRUCTSIZE = 0x1